
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 09 21:11:23 CST 2016
//----------------------------------------------------

package analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MENOR = 86;
  public static final int IDENTIFICADOR = 54;
  public static final int PR_INPUT = 12;
  public static final int CONT_LLAVE_CIERRA = 39;
  public static final int CONT_PARENTESIS_ABRE = 42;
  public static final int PR_FOR = 22;
  public static final int PR_LONG = 35;
  public static final int PR_TRY = 26;
  public static final int PR_EXEC = 21;
  public static final int PR_BREAK = 14;
  public static final int OP_MUL = 63;
  public static final int PR_INT = 24;
  public static final int OP_DIST = 84;
  public static final int PR_CHAR = 33;
  public static final int OP_MOD = 66;
  public static final int BOOL_TRUE = 48;
  public static final int OPBITS_OR = 70;
  public static final int COMENTARIO_LINEA = 57;
  public static final int PR_EXCEPT = 7;
  public static final int PR_PRINT = 11;
  public static final int NUMERO_ENTERO = 44;
  public static final int PR_ELSE = 20;
  public static final int OP_SUMA = 64;
  public static final int OP_RESTA = 62;
  public static final int OP_MENORIG = 89;
  public static final int CONT_CORCHETE_ABRE = 40;
  public static final int CONT_PARENTESIS_CIERRA = 43;
  public static final int OP_DIV = 65;
  public static final int NUMERO_LONG = 45;
  public static final int OPBITS_NOT = 72;
  public static final int OP_DIVENT = 68;
  public static final int OP_ASG_POT = 81;
  public static final int ERROR = 61;
  public static final int PR_CONTINUE = 27;
  public static final int BOOL_FALSE = 49;
  public static final int DOS_PUNTOS = 51;
  public static final int OP_DIF = 87;
  public static final int NUMERO_COMPLEJO = 47;
  public static final int PR_LIST = 30;
  public static final int COMENTARIO_BLOQUE = 56;
  public static final int OPBITS_DESPLAZ_IZQ = 74;
  public static final int PR_RANGE = 34;
  public static final int PUNTO_COMA = 52;
  public static final int OP_ASG_SUMA = 76;
  public static final int COMA = 50;
  public static final int PR_RETURN = 6;
  public static final int OP_ASG_MUL = 78;
  public static final int OP_ASG_MOD = 80;
  public static final int OP_MAYORIG = 88;
  public static final int OP_MAYOR = 85;
  public static final int PR_WITH = 16;
  public static final int PR_IMPORT = 4;
  public static final int PR_BOOLEAN = 32;
  public static final int PR_ASSERT = 8;
  public static final int OP_CMPIGUAL = 83;
  public static final int Error_Identificador = 55;
  public static final int PR_RAISE = 15;
  public static final int OPBITS_DESPLAZ_DERECHA = 73;
  public static final int PR_FROM = 18;
  public static final int PR_GLOBAL = 3;
  public static final int OP_ASG_DIVENT = 82;
  public static final int OP_AND = 90;
  public static final int EOF = 0;
  public static final int OP_ASG_DIV = 79;
  public static final int PUNTO = 53;
  public static final int PR_CATCH = 37;
  public static final int COMP_IS = 59;
  public static final int PR_PASS = 17;
  public static final int NUMERO_FLOTANTE = 46;
  public static final int PR_DEL = 23;
  public static final int CONT_LLAVE_ABRE = 38;
  public static final int error = 1;
  public static final int COMP_IN = 60;
  public static final int PR_YIELD = 10;
  public static final int PR_STRING = 31;
  public static final int PR_DEF = 2;
  public static final int PR_ELIF = 19;
  public static final int PR_FLOAT = 29;
  public static final int PR_FINALLY = 28;
  public static final int OP_ASG_RESTA = 77;
  public static final int PR_IF = 25;
  public static final int OP_IGUAL = 75;
  public static final int PR_CLASS = 13;
  public static final int STRING = 58;
  public static final int OP_POT = 67;
  public static final int OPBITS_AND = 69;
  public static final int CONT_CORCHETE_CIERRA = 41;
  public static final int OP_OR = 92;
  public static final int OPBITS_XOR = 71;
  public static final int PR_WHILE = 9;
  public static final int OP_NOT = 91;
  public static final int PR_COMPLEX = 36;
  public static final int PR_LAMBDA = 5;
}

