
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 07 01:05:38 CST 2016
//----------------------------------------------------

package analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MENOR = 61;
  public static final int OP_DIVISION = 57;
  public static final int IDENTIFICADOR = 47;
  public static final int PR_INPUT = 12;
  public static final int CONT_LLAVE_CIERRA = 35;
  public static final int CONT_PARENTESIS_ABRE = 38;
  public static final int PR_FOR = 22;
  public static final int PR_TRY = 26;
  public static final int PR_EXEC = 21;
  public static final int PR_BREAK = 14;
  public static final int PR_INT = 24;
  public static final int OP_ASIGNAR_SUMA = 69;
  public static final int PR_CHAR = 33;
  public static final int OP_POTENCIA = 67;
  public static final int OPBITS_OR = 63;
  public static final int PR_PRINT = 11;
  public static final int PR_EXCEPT = 7;
  public static final int NUMERO_ENTERO = 40;
  public static final int PR_ELSE = 20;
  public static final int OP_DIV_ENTERA = 71;
  public static final int OP_SUMA = 56;
  public static final int SEPARADOR_DOS_PUNTOS = 45;
  public static final int OP_RESTA = 54;
  public static final int OP_DISTINTO = 75;
  public static final int CONT_CORCHETE_ABRE = 36;
  public static final int CONT_PARENTESIS_CIERRA = 39;
  public static final int OP_ASIGNAR_POTENCIA = 82;
  public static final int OP_MAYORIGUAL = 76;
  public static final int NUMERO_LONG = 41;
  public static final int OPBITS_NOT = 65;
  public static final int OP_ASIGNAR_DIVISION = 72;
  public static final int ERROR = 53;
  public static final int PR_CONTINUE = 27;
  public static final int NUMERO_COMPLEJO = 43;
  public static final int PR_LIST = 30;
  public static final int COMENTARIO_BLOQUE = 49;
  public static final int OPBITS_DESPLAZ_IZQ = 80;
  public static final int PUNTO_COMA = 46;
  public static final int SEPARADOR_COMA = 44;
  public static final int PR_RETURN = 6;
  public static final int OP_COMPARACION_IGUALDAD = 74;
  public static final int OP_ASIGNAR_MULTIPLICACION = 68;
  public static final int OP_ASIGNAR_DIV_ENTERA = 81;
  public static final int OP_MAYOR = 60;
  public static final int PR_WITH = 16;
  public static final int PR_IMPORT = 4;
  public static final int PR_BOOLEAN = 32;
  public static final int PR_ASSERT = 8;
  public static final int Error_Identificador = 48;
  public static final int PR_RAISE = 15;
  public static final int OPBITS_DESPLAZ_DERECHA = 77;
  public static final int PR_FROM = 18;
  public static final int PR_GLOBAL = 3;
  public static final int OP_AND = 83;
  public static final int EOF = 0;
  public static final int COMP_IS = 51;
  public static final int NUMERO_FLOTANTE = 42;
  public static final int PR_PASS = 17;
  public static final int OP_ASIGNAR_MODULO = 73;
  public static final int CONT_LLAVE_ABRE = 34;
  public static final int PR_DEL = 23;
  public static final int OP_MULTIPLICACION = 55;
  public static final int COMP_IN = 52;
  public static final int error = 1;
  public static final int PR_YIELD = 10;
  public static final int PR_STRING = 31;
  public static final int PR_DEF = 2;
  public static final int PR_ELIF = 19;
  public static final int OP_DIFERENTE = 79;
  public static final int PR_FLOAT = 29;
  public static final int PR_FINALLY = 28;
  public static final int PR_IF = 25;
  public static final int OP_ASIGNAR_RESTA = 66;
  public static final int OP_IGUAL = 59;
  public static final int PR_CLASS = 13;
  public static final int STRING = 50;
  public static final int OPBITS_AND = 62;
  public static final int OP_MODULO = 58;
  public static final int CONT_CORCHETE_CIERRA = 37;
  public static final int OP_MENORIGUAL = 78;
  public static final int OP_OR = 70;
  public static final int OPBITS_XOR = 64;
  public static final int PR_WHILE = 9;
  public static final int OP_NOT = 84;
  public static final int PR_LAMBDA = 5;
}

